name: Build

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        php: ['8.1', '8.2']

    name: PHP ${{ matrix.php }} tests on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependancies
        run: composer install --prefer-source --no-interaction

      - name: Run phpunit tests
        run: vendor/bin/phpunit